server:
  port: 8090

bot:
  configuration:
    username: @username_bot
    token: token_bot
    owner: owner_chat_id
    admin: admin_chat_id

file:
  path:
    archive: temp
    images: images

logging:
  level:
    org:
      springframework:
        web: DEBUG
